# Generated by Django 2.2.5 on 2019-10-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='NewsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'newstypes',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='images')),
                ('news_body', models.TextField(max_length=600)),
                ('is_trending', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.Country')),
                ('news_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.NewsTypes')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
